# http://docs.travis-ci.com/user/languages/scala/
language: scala

scala:
  - 2.10.6
  - 2.11.8

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

cache:
  directories:
    - $HOME/.ivy2

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean compile test
